# Generated by Django 5.1.15 on 2026-06-24 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('healthcare', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='symptomcheck',
            name='age',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='symptomcheck',
            name='duration_hours',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='symptomcheck',
            name='explanation',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='symptomcheck',
            name='recommended_specialty',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='symptomcheck',
            name='red_flags',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='symptomcheck',
            name='severity',
            field=models.CharField(blank=True, choices=[('mild', 'Mild'), ('moderate', 'Moderate'), ('severe', 'Severe')], max_length=10),
        ),
        migrations.AddField(
            model_name='symptomcheck',
            name='triage',
            field=models.CharField(blank=True, choices=[('self_care', 'Self care'), ('gp', 'See a GP'), ('urgent', 'Urgent / ER')], max_length=10),
        ),
        migrations.AddIndex(
            model_name='symptomcheck',
            index=models.Index(fields=['triage', '-created_at'], name='healthcare__triage_03c382_idx'),
        ),
    ]
